# 1. Python 3.11 공식 이미지를 기반으로 합니다.
FROM python:3.10

# 2. 환경변수 설정
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# 3. 작업 디렉터리 생성 및 설정
WORKDIR /app

# 4. 의존성 설치
# requirements.txt를 먼저 복사하여 패키지를 설치합니다.
COPY docker/requirement_api.txt /app/
RUN pip install --no-cache-dir -r requirement_api.txt

# 5. 프로젝트 소스 코드 복사
COPY . /app/

# 6. FastAPI 애플리케이션이 사용할 포트를 8001으로 지정
EXPOSE 8001

# 7. 컨테이너가 시작될 때 실행할 기본 명령어 설정
# uvicorn을 사용하여 src/rag/api.py에 있는 app 객체를 실행합니다.
CMD ["python", "-m", "src.rag.api"]
