# Generated by Django 5.2.9 on 2026-01-07 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='project_id',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ChatProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Project',
                'verbose_name_plural': 'Chat Projects',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'folder_name')},
            },
        ),
    ]
