server {
    listen 80;
    server_name _; # 실제 도메인이 생기면 도메인 입력

    # Django 정적 파일 서빙 (CSS/JS가 안 깨지게 해줌)
    location /static/ {
        alias /app/static/;
    }

    # 모든 요청을 Django로 전달
    location / {
        proxy_pass http://web-backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}